<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsAotCompatible>true</IsAotCompatible>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>

    <Version>1.2.2</Version>
    <PackageId>BitcoderCZ.Minecraft.MeshGenerator</PackageId>
    <PackageTags>library;minecraft</PackageTags>
    <Description>Generate mesh from a minecraft world.</Description>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BitcoderCZ.Minecraft.MeshGenerator.Gltf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BitcoderCZ.Buffers" />
    <PackageReference Include="BitcoderCZ.Maths" />
    <PackageReference Include="BitcoderCZ.Utils" />
    <PackageReference Include="Cyotek.Data.Nbt" />
    <PackageReference Include="SixLabors.ImageSharp" />
  </ItemGroup>

</Project>
